Repository matchday-team/matchday-api, pull requests merged in 2025-04, with the labels that each got.

#12 README 작성 및 PR Template 등록
  .github/ISSUE_TEMPLATE/issue-template.md
  .github/pull_request_template.md
  README.md
Labels: documentation

#18 공통 Response, Exception, Status Interface 구현
  .gitignore
  build.gradle
  src/main/java/com/matchday/matchdayserver/common/exception/ApiException.java
  src/main/java/com/matchday/matchdayserver/common/exception/ApiExceptionHandler.java
  src/main/java/com/matchday/matchdayserver/common/exception/ApiExceptionInterface.java
  src/main/java/com/matchday/matchdayserver/common/response/ApiResponse.java
  src/main/java/com/matchday/matchdayserver/common/response/DefaultStatus.java
  src/main/java/com/matchday/matchdayserver/common/response/StatusInterface.java
  src/main/resources/application.yml
Labels: ✨ Feat

#21 Feat/user 14
  src/main/java/com/matchday/matchdayserver/common/response/UserStatus.java
  src/main/java/com/matchday/matchdayserver/user/controller/UserController.java
  src/main/java/com/matchday/matchdayserver/user/model/Entity/User.java
  src/main/java/com/matchday/matchdayserver/user/model/dto/request/UserCreateRequest.java
  src/main/java/com/matchday/matchdayserver/user/repository/UserRepository.java
  src/main/java/com/matchday/matchdayserver/user/service/UserService.java
Labels: ✨ Feat

#25 chore:서버 재시작 위한 워크플로우 추가
  .github/workflows/restart.yml
  src/main/java/com/matchday/matchdayserver/user/service/UserService.java
Labels: 🗑️ Chore

#37 [MAT-71] NCP 서버 이전 테스트
  src/main/java/com/matchday/matchdayserver/user/service/UserService.java
Labels: 📬 Back-End

#51 [MAT-71] github action에서 application.yml에 값을 직접 로드하도록 수정
  .github/workflows/deploy.yml
  .gitignore
  src/main/resources/application.yml
Labels: 🌏 Deploy

#52 [MAT-71] human err 오타수정
  .github/workflows/deploy.yml
  src/main/resources/application.yml
Labels: 🐞 Bug

#54 [MAT-76] WebConfig CORS 추가
  src/main/java/com/matchday/matchdayserver/config/WebConfig.java
Labels: ⚙ Config

#55 fix(MAT-76): 구체적인 포트 지정(와일드 카드 미사용)
  src/main/java/com/matchday/matchdayserver/config/WebConfig.java
Labels: 🐞 Bug

#58 feat(gitignore): DS_Store 추가
  .gitignore
Labels: 🗑️ Chore

#61 [MAT-102] 알 수 없는 에러 예외 처리 ApiExceptionHandler
  src/main/java/com/matchday/matchdayserver/common/exception/ApiExceptionHandler.java
  src/main/java/com/matchday/matchdayserver/common/response/DefaultStatus.java
Labels: ✨ Feat

#63 [MAT-97] Match Event 기록 요구사항에 맞게 변경
  src/main/java/com/matchday/matchdayserver/matchevent/mapper/MatchEventMapper.java
  src/main/java/com/matchday/matchdayserver/matchevent/model/dto/MatchEventResponse.java
  src/main/java/com/matchday/matchdayserver/matchevent/model/entity/MatchEvent.java
  src/main/java/com/matchday/matchdayserver/matchevent/model/enums/MatchEventType.java
  src/main/java/com/matchday/matchdayserver/matchevent/service/MatchEventSaveService.java
  src/main/java/com/matchday/matchdayserver/matchevent/service/MatchEventStrategy.java
Labels: 🎨 Modify

#62 [MAT-103] WebSocket 에러처리 고도화
  src/main/java/com/matchday/matchdayserver/common/exception/CustomWebSocketHandlerDecorator.java
  src/main/java/com/matchday/matchdayserver/common/exception/WebSocketExceptionHandler.java
  src/main/java/com/matchday/matchdayserver/common/model/Message.java
  src/main/java/com/matchday/matchdayserver/common/response/DefaultStatus.java
  src/main/java/com/matchday/matchdayserver/common/response/MatchStatus.java
  src/main/java/com/matchday/matchdayserver/config/ObjectMapperConfig.java
  src/main/java/com/matchday/matchdayserver/config/WebSocketConfig.java
  src/main/java/com/matchday/matchdayserver/matchevent/model/dto/MatchEventRequest.java
  src/main/java/com/matchday/matchdayserver/matchevent/service/MatchEventSaveService.java
Labels: 🎨 Modify
