Repository matchday-team/matchday-api, pull requests merged in 2025-05, with the labels that each got.

#72 [MAT-149] MatchUser에 Team 추가
  src/main/java/com/matchday/matchdayserver/matchuser/model/dto/MatchUserCreateRequest.java
  src/main/java/com/matchday/matchdayserver/matchuser/model/entity/MatchUser.java
  src/main/java/com/matchday/matchdayserver/matchuser/model/enums/MatchUserRole.java
  src/main/java/com/matchday/matchdayserver/matchuser/model/mapper/MatchUserMapper.java
  src/main/java/com/matchday/matchdayserver/matchuser/service/MatchUserService.java
  src/main/java/com/matchday/matchdayserver/team/repository/TeamRepository.java
Labels: 🎨 Modify

#74 [MAT-150] MatchScore 조회 API 구현
  .editorconfig
  docker-compose.yaml
  src/main/java/com/matchday/matchdayserver/match/controller/MatchController.java
  src/main/java/com/matchday/matchdayserver/match/model/dto/response/MatchScoreResponse.java
  src/main/java/com/matchday/matchdayserver/match/service/MatchScoreService.java
  src/main/java/com/matchday/matchdayserver/matchevent/controller/MatchEventHistoryController.java
  src/main/java/com/matchday/matchdayserver/matchevent/model/dto/ScoreResponse.java
  src/main/java/com/matchday/matchdayserver/matchevent/model/enums/MatchEventType.java
  src/main/java/com/matchday/matchdayserver/matchevent/repository/MatchEventRepository.java
  src/main/java/com/matchday/matchdayserver/matchevent/service/MatchEventHistoryService.java
Labels: ✨ Feat, 🗑️ Chore

#75 docs: web socket 문서 추가
  docs/README.md
  docs/web-socket-spect.md
Labels: 📃 Docs

#76 [MAT-132] 선수 교체 WebSocket Endpoint 구현
  src/main/java/com/matchday/matchdayserver/common/response/MatchStatus.java
  src/main/java/com/matchday/matchdayserver/matchuser/controller/MatchUserExchangeController.java
  src/main/java/com/matchday/matchdayserver/matchuser/model/dto/MatchUserExchangeRequest.java
  src/main/java/com/matchday/matchdayserver/matchuser/model/entity/MatchUser.java
  src/main/java/com/matchday/matchdayserver/matchuser/service/MatchUserExchangeService.java
Labels: ✨ Feat

#84 [MAT-163] Global Exception Handler 오류 수정
  src/main/java/com/matchday/matchdayserver/common/exception/ApiExceptionHandler.java
Labels: 🐞 Bug

#85 [MAT-164] 매치선수 그리드 좌표 수정 API
  src/main/java/com/matchday/matchdayserver/common/response/MatchUserStatus.java
  src/main/java/com/matchday/matchdayserver/matchuser/controller/MatchUserController.java
  src/main/java/com/matchday/matchdayserver/matchuser/model/dto/MatchUserCreateRequest.java
  src/main/java/com/matchday/matchdayserver/matchuser/model/dto/MatchUserGridUpdateRequest.java
  src/main/java/com/matchday/matchdayserver/matchuser/model/dto/MatchUserResponse.java
  src/main/java/com/matchday/matchdayserver/matchuser/model/entity/MatchUser.java
  src/main/java/com/matchday/matchdayserver/matchuser/model/mapper/MatchUserMapper.java
  src/main/java/com/matchday/matchdayserver/matchuser/service/MatchUserService.java
Labels: ✨ Feat

#86 [MAT-167] User, Team 프로필 이미지 필드 추가 및 저장 로직 추가
  src/main/java/com/matchday/matchdayserver/s3/service/S3PresignedService.java
  src/main/java/com/matchday/matchdayserver/team/controller/TeamController.java
  src/main/java/com/matchday/matchdayserver/team/model/dto/request/TeamCreateRequest.java
  src/main/java/com/matchday/matchdayserver/team/model/dto/response/TeamResponse.java
  src/main/java/com/matchday/matchdayserver/team/model/entity/Team.java
  src/main/java/com/matchday/matchdayserver/team/model/mapper/TeamMapper.java
  src/main/java/com/matchday/matchdayserver/team/service/TeamService.java
  src/main/java/com/matchday/matchdayserver/user/controller/UserController.java
  src/main/java/com/matchday/matchdayserver/user/model/dto/request/UserCreateRequest.java
  src/main/java/com/matchday/matchdayserver/user/model/dto/response/UserInfoResponse.java
  src/main/java/com/matchday/matchdayserver/user/model/entity/User.java
  src/main/java/com/matchday/matchdayserver/user/model/mapper/UserMapper.java
  src/main/java/com/matchday/matchdayserver/user/service/UserService.java
Labels: ✨ Feat

#87 [MAT-164] MatchUser 그리드 좌표 형식 수정
  src/main/java/com/matchday/matchdayserver/matchuser/controller/MatchUserController.java
  src/main/java/com/matchday/matchdayserver/matchuser/model/dto/MatchUserCreateRequest.java
  src/main/java/com/matchday/matchdayserver/matchuser/model/dto/MatchUserGridUpdateRequest.java
  src/main/java/com/matchday/matchdayserver/matchuser/model/dto/MatchUserResponse.java
  src/main/java/com/matchday/matchdayserver/matchuser/model/entity/MatchUser.java
  src/main/java/com/matchday/matchdayserver/matchuser/model/mapper/MatchUserMapper.java
  src/main/java/com/matchday/matchdayserver/matchuser/service/MatchUserService.java
Labels: 🔨 Refactor

#89 [MAT-166] profileImgUrl 넣기
  src/main/java/com/matchday/matchdayserver/matchuser/model/dto/MatchUserResponse.java
  src/main/java/com/matchday/matchdayserver/matchuser/service/MatchUserService.java
  src/main/java/com/matchday/matchdayserver/team/model/dto/response/TeamMemberResponse.java
  src/main/java/com/matchday/matchdayserver/userteam/model/mapper/UserTeamMapper.java
Labels: ✨ Feat

#90 [MAT-170] DTO 스키마 nullable 정보 추가
  src/main/java/com/matchday/matchdayserver/match/controller/MatchController.java
  src/main/java/com/matchday/matchdayserver/match/model/dto/request/MatchCreateRequest.java
  src/main/java/com/matchday/matchdayserver/match/model/dto/request/MatchHalfTimeRequest.java
  src/main/java/com/matchday/matchdayserver/match/model/dto/request/MatchMemoRequest.java
  src/main/java/com/matchday/matchdayserver/matchuser/model/dto/MatchUserCreateRequest.java
  src/main/java/com/matchday/matchdayserver/team/model/dto/request/TeamCreateRequest.java
  src/main/java/com/matchday/matchdayserver/user/model/dto/request/UserCreateRequest.java
  src/main/java/com/matchday/matchdayserver/user/model/dto/request/UserJoinTeamRequest.java
Labels: 📃 Docs

#91 style(MatchEventStrategy): ident 4 칸으로 변경
  src/main/java/com/matchday/matchdayserver/matchevent/mapper/MatchEventMapper.java
  src/main/java/com/matchday/matchdayserver/matchevent/model/dto/MatchEventResponse.java
  src/main/java/com/matchday/matchdayserver/matchevent/service/MatchEventSaveService.java
  src/main/java/com/matchday/matchdayserver/matchevent/service/MatchEventStrategy.java
Labels: 🗑️ Chore

#94 [MAT-178] Match Info 수정
  src/main/java/com/matchday/matchdayserver/match/model/dto/request/MatchCreateRequest.java
  src/main/java/com/matchday/matchdayserver/match/model/dto/response/MatchInfoResponse.java
  src/main/java/com/matchday/matchdayserver/match/model/dto/response/MatchListResponse.java
  src/main/java/com/matchday/matchdayserver/match/model/entity/Match.java
  src/main/java/com/matchday/matchdayserver/match/model/mapper/MatchMapper.java
  src/main/java/com/matchday/matchdayserver/match/service/MatchCreateService.java
  src/main/java/com/matchday/matchdayserver/matchevent/mapper/MatchEventMapper.java
Labels: 🔨 Refactor

#95 [MAT-179] 경기 시작 시간(firstHalfStartTiime) 초기화
  src/main/java/com/matchday/matchdayserver/matchevent/controller/MatchEventRestController.java
  src/main/java/com/matchday/matchdayserver/matchevent/service/MatchEventDeleteService.java
Labels: ✨ Feat

#97 [MAT-180] MatchUserResponse 교체인/아웃 여부에 대한 필드 추가
  src/main/java/com/matchday/matchdayserver/matchevent/repository/MatchEventRepository.java
  src/main/java/com/matchday/matchdayserver/matchuser/model/dto/MatchUserResponse.java
  src/main/java/com/matchday/matchdayserver/matchuser/service/MatchUserService.java
Labels: ✨ Feat

#93 [MAT-173] DTO 스키마 Null 여부 추가
  src/main/java/com/matchday/matchdayserver/match/model/dto/request/MatchCreateRequest.java
  src/main/java/com/matchday/matchdayserver/match/model/dto/response/MatchInfoResponse.java
  src/main/java/com/matchday/matchdayserver/match/model/dto/response/MatchListResponse.java
  src/main/java/com/matchday/matchdayserver/match/model/dto/response/MatchMemoResponse.java
  src/main/java/com/matchday/matchdayserver/match/model/dto/response/MatchScoreResponse.java
  src/main/java/com/matchday/matchdayserver/matchevent/model/dto/MatchEventDeleteResponse.java
  src/main/java/com/matchday/matchdayserver/matchevent/model/dto/MatchEventRequest.java
  src/main/java/com/matchday/matchdayserver/matchevent/model/dto/MatchEventResponse.java
  src/main/java/com/matchday/matchdayserver/matchevent/model/dto/ScoreResponse.java
  src/main/java/com/matchday/matchdayserver/matchuser/model/dto/MatchUserCreateRequest.java
  src/main/java/com/matchday/matchdayserver/matchuser/model/dto/MatchUserExchangeRequest.java
  src/main/java/com/matchday/matchdayserver/matchuser/model/dto/MatchUserGridUpdateRequest.java
  src/main/java/com/matchday/matchdayserver/matchuser/model/dto/MatchUserResponse.java
  src/main/java/com/matchday/matchdayserver/s3/dto/S3PresignedResponse.java
  src/main/java/com/matchday/matchdayserver/s3/service/S3PresignedService.java
  src/main/java/com/matchday/matchdayserver/team/model/dto/request/TeamCreateRequest.java
  src/main/java/com/matchday/matchdayserver/team/model/dto/response/TeamMemberResponse.java
  src/main/java/com/matchday/matchdayserver/team/model/dto/response/TeamResponse.java
  src/main/java/com/matchday/matchdayserver/team/model/dto/response/TeamSearchResponse.java
  src/main/java/com/matchday/matchdayserver/team/model/mapper/TeamMapper.java
  src/main/java/com/matchday/matchdayserver/user/model/dto/request/UserCreateRequest.java
  src/main/java/com/matchday/matchdayserver/user/model/dto/request/UserJoinTeamRequest.java
  src/main/java/com/matchday/matchdayserver/user/model/dto/response/UserInfoResponse.java
  src/main/java/com/matchday/matchdayserver/userteam/model/dto/JoinUserTeamResponse.java
Labels: 📃 Docs

#92 [MAT-172] 이벤트 전송 필요한 Log만 전송하도록 변경
  src/main/java/com/matchday/matchdayserver/matchevent/mapper/MatchEventMapper.java
  src/main/java/com/matchday/matchdayserver/matchevent/model/dto/MatchEventResponse.java
  src/main/java/com/matchday/matchdayserver/matchevent/model/enums/MatchEventType.java
  src/main/java/com/matchday/matchdayserver/matchevent/service/MatchEventSaveService.java
  src/main/java/com/matchday/matchdayserver/matchevent/service/MatchEventStrategy.java
Labels: ✨ Feat

#98 [MAT-186]
  build.gradle
  src/main/java/com/matchday/matchdayserver/matchevent/service/MatchEventQueryService.java
  src/main/java/com/matchday/matchdayserver/matchevent/service/MatchEventSaveService.java
  src/main/java/com/matchday/matchdayserver/matchuser/repository/MatchUserRepository.java
  src/main/java/com/matchday/matchdayserver/matchuser/service/MatchUserService.java
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
Labels: ⚙ Config, 🐞 Bug

#101 [MAT-189] OWN_GOAL도 점수 집계에 반영되도록 수정
  src/main/java/com/matchday/matchdayserver/match/model/dto/response/MatchScoreResponse.java
Labels: 🐞 Bug

#99 [MAT-187] 팀 ID로 Event 기록하는 End Point 추가
  src/main/java/com/matchday/matchdayserver/match/service/MatchCreateService.java
  src/main/java/com/matchday/matchdayserver/matchevent/controller/MatchEventWebSocketController.java
  src/main/java/com/matchday/matchdayserver/matchevent/mapper/MatchEventMapper.java
  src/main/java/com/matchday/matchdayserver/matchevent/model/dto/MatchEventRequest.java
  src/main/java/com/matchday/matchdayserver/matchevent/model/dto/MatchEventUserRequest.java
  src/main/java/com/matchday/matchdayserver/matchevent/service/MatchEventSaveService.java
  src/main/java/com/matchday/matchdayserver/matchuser/model/entity/MatchUser.java
  src/main/java/com/matchday/matchdayserver/matchuser/repository/MatchUserRepository.java
  src/main/java/com/matchday/matchdayserver/matchuser/service/MatchUserService.java
  src/main/java/com/matchday/matchdayserver/user/model/entity/User.java
Labels: ✨ Feat, 🐞 Bug

#104 [MAT-187] 팀 단위로 event 기록하는 web socket endpoint 문서화
  docs/web-socket-spect.md
Labels: 📃 Docs

#103 [MAT-174] 매치 경기 시간(전/후반 시작/종료) 등록 API 수정
  src/main/java/com/matchday/matchdayserver/match/controller/MatchController.java
  src/main/java/com/matchday/matchdayserver/match/model/dto/request/MatchHalfTimeRequest.java
  src/main/java/com/matchday/matchdayserver/match/model/enums/HalfType.java
  src/main/java/com/matchday/matchdayserver/match/model/enums/TimeType.java
  src/main/java/com/matchday/matchdayserver/match/service/MatchService.java
Labels: 🔨 Refactor

#107 [MAT-197] 경기 기록 취소 구현
  .gitignore
  docs/web-socket-spect.md
  src/main/java/com/matchday/matchdayserver/common/model/Message.java
  src/main/java/com/matchday/matchdayserver/common/response/MatchStatus.java
  src/main/java/com/matchday/matchdayserver/matchevent/controller/MatchEventWebSocketController.java
  src/main/java/com/matchday/matchdayserver/matchevent/model/dto/MatchEventCancelRequest.java
  src/main/java/com/matchday/matchdayserver/matchevent/model/dto/MatchEventUserRequest.java
  src/main/java/com/matchday/matchdayserver/matchevent/repository/MatchEventRepository.java
  src/main/java/com/matchday/matchdayserver/matchevent/service/MatchEventCancelService.java
  src/main/java/com/matchday/matchdayserver/matchevent/service/MatchEventSaveService.java
  src/main/java/com/matchday/matchdayserver/matchuser/controller/MatchUserExchangeController.java
  src/main/java/com/matchday/matchdayserver/matchuser/repository/MatchUserRepository.java
  src/main/java/com/matchday/matchdayserver/matchuser/service/MatchUserExchangeService.java
  test.sql
Labels: ✨ Feat, 🎨 Modify

#108 [MAT-210] match player 조회시 matchUserId 조회 가능하도록 추가
  src/main/java/com/matchday/matchdayserver/matchuser/model/dto/MatchUserResponse.java
  src/main/java/com/matchday/matchdayserver/matchuser/service/MatchUserService.java
Labels: ✨ Feat

#112 [MAT-213] 그리드 위치 변경 시 중복 방지를 위한 검증 로직 추가
  src/main/java/com/matchday/matchdayserver/common/response/MatchUserStatus.java
  src/main/java/com/matchday/matchdayserver/matchuser/repository/MatchUserRepository.java
  src/main/java/com/matchday/matchdayserver/matchuser/service/MatchUserService.java
Labels: ✨ Feat

#114 [MAT-229] Flyway 도입
  build.gradle
  src/main/java/com/matchday/matchdayserver/config/FlywayConfig.java
  src/main/resources/application.yml
  src/main/resources/db/migration/V1__.sql
Labels: ⚙ Config

#113 [MAT-288] 선수 교체시 교체 선수의 grid만 복사되게 수정
  src/main/java/com/matchday/matchdayserver/matchuser/model/entity/MatchUser.java
  src/main/java/com/matchday/matchdayserver/matchuser/service/MatchUserExchangeService.java
Labels: 🎨 Modify

#115 [MAT-230] Test Coverage 측정을 위한 Jacoco 도입
  .github/workflows/test.yml
  build.gradle
Labels: ⚙ Config

#117 [MAT-232] 파생되는 이벤트말고 메인 이벤트만 ws로 전송하도록 변경
  src/main/java/com/matchday/matchdayserver/matchevent/service/MatchEventSaveService.java
Labels: 🎨 Modify

#118 [MAT-234] 전체 매치 리스트 조회 API
  src/main/java/com/matchday/matchdayserver/common/response/MatchStatus.java
  src/main/java/com/matchday/matchdayserver/match/controller/MatchController.java
  src/main/java/com/matchday/matchdayserver/match/model/dto/response/MatchListPageResponse.java
  src/main/java/com/matchday/matchdayserver/match/repository/MatchRepository.java
  src/main/java/com/matchday/matchdayserver/match/service/MatchService.java
Labels: ✨ Feat

#120 [MAT-235] 매치 정보 응답 DTO에 경기명 추가
  src/main/java/com/matchday/matchdayserver/match/model/dto/response/MatchInfoResponse.java
  src/main/java/com/matchday/matchdayserver/match/model/mapper/MatchMapper.java
Labels: 🎨 Modify

#121 [MAT-236] 유저 이벤트 생성 시 Log 전송 안되는 버그 수정
  src/main/java/com/matchday/matchdayserver/matchevent/common/MatchEventConstants.java
  src/main/java/com/matchday/matchdayserver/matchevent/service/MatchEventSaveService.java
  src/main/java/com/matchday/matchdayserver/matchuser/service/MatchUserExchangeService.java
Labels: 🐞 Bug

#122 feat(match): 특정 팀의 매치 결과 리스트 조회 구현
  src/main/java/com/matchday/matchdayserver/match/controller/MatchController.java
  src/main/java/com/matchday/matchdayserver/match/model/dto/response/MatchResultInfoResponse.java
  src/main/java/com/matchday/matchdayserver/match/model/enums/MatchResult.java
  src/main/java/com/matchday/matchdayserver/match/model/mapper/MatchMapper.java
  src/main/java/com/matchday/matchdayserver/match/repository/MatchRepository.java
  src/main/java/com/matchday/matchdayserver/match/service/MatchResultService.java
  src/main/java/com/matchday/matchdayserver/matchuser/repository/MatchUserRepository.java
Labels: ✨ Feat

#116 [MAT-231] 통합 테스트 세팅 및 임시 유저 생성 테스트 구현
  src/main/java/com/matchday/matchdayserver/common/response/ApiResponse.java
  src/main/java/com/matchday/matchdayserver/user/controller/UserController.java
  src/main/java/com/matchday/matchdayserver/user/model/dto/request/UserCreateRequest.java
  src/main/java/com/matchday/matchdayserver/user/service/UserService.java
  src/main/resources/application-test.yml
  src/test/java/com/matchday/matchdayserver/user/controller/UserControllerCreateTest.java
Labels: 🎨 Modify, ✅ Test

#123 [MAT-239] warning 팀 스토어에 집계되지 않는 문제 해결
  src/main/java/com/matchday/matchdayserver/match/model/dto/response/MatchScoreResponse.java
Labels: 🐞 Bug

#125 [MAT-245] memo 동기화 websocket 엔드포인트 변경
  src/main/java/com/matchday/matchdayserver/match/service/MatchService.java
  src/main/java/com/matchday/matchdayserver/matchevent/common/MatchEventConstants.java
Labels: 🔨 Refactor

#128 [MAT-251] MatchUser 조회 응답에 자책골 추가
  src/main/java/com/matchday/matchdayserver/match/model/entity/Match.java
  src/main/java/com/matchday/matchdayserver/matchevent/service/MatchEventQueryService.java
  src/main/java/com/matchday/matchdayserver/matchuser/model/dto/MatchUserEventStat.java
  src/main/java/com/matchday/matchdayserver/matchuser/model/dto/MatchUserResponse.java
  src/main/java/com/matchday/matchdayserver/matchuser/service/MatchUserService.java
Labels: ✨ Feat

#127 [MAT-246] 진행 중 경기에만 이벤트 발생시킬 수 있도록 변경
  src/main/java/com/matchday/matchdayserver/common/response/MatchStatus.java
  src/main/java/com/matchday/matchdayserver/match/model/entity/Match.java
  src/main/java/com/matchday/matchdayserver/match/service/MatchService.java
  src/main/java/com/matchday/matchdayserver/match/util/MatchStateValidator.java
  src/main/java/com/matchday/matchdayserver/matchevent/service/MatchEventCancelService.java
  src/main/java/com/matchday/matchdayserver/matchevent/service/MatchEventSaveService.java
  src/main/java/com/matchday/matchdayserver/matchuser/service/MatchUserExchangeService.java
  src/main/resources/db/migration/V2__match_state_enum_change.sql
  src/test/java/com/matchday/matchdayserver/IntegrationTestSupport.java
  src/test/java/com/matchday/matchdayserver/user/controller/UserControllerCreateTest.java
Labels: ✨ Feat

#133 [MAT-254] elapsedMinutes 항상 0으로 나오는 문제 해결
  src/main/java/com/matchday/matchdayserver/common/response/MatchStatus.java
  src/main/java/com/matchday/matchdayserver/matchevent/mapper/MatchEventMapper.java
  src/main/java/com/matchday/matchdayserver/matchevent/model/dto/MatchEventResponse.java
Labels: ✨ Feat, 🐞 Bug

#134 [MAT-254] 하드코딩 개선
  src/main/java/com/matchday/matchdayserver/matchevent/mapper/MatchEventMapper.java
Labels: 🔨 Refactor

#135 [MAT-254] 전 후반 판단 로직 변경
  src/main/java/com/matchday/matchdayserver/matchevent/mapper/MatchEventMapper.java
Labels: 🐞 Bug

#137 [MAT-263] 매치 이벤트 오프사이드시 파울+1 되는 로직 삭제
  src/main/java/com/matchday/matchdayserver/matchevent/service/MatchEventStrategy.java
Labels: 🎨 Modify

#140 DB-migration-V7
  src/main/java/com/matchday/matchdayserver/matchevent/model/entity/MatchEvent.java
  src/main/resources/db/migration/V7__parent_id_add.sql
Labels: ✨ Feat

#142 [MAT- 289] 매치 이벤트 파생 데이터 삭제 구현
  docs/web-socket-spect.md
  src/main/java/com/matchday/matchdayserver/matchevent/mapper/MatchEventMapper.java
  src/main/java/com/matchday/matchdayserver/matchevent/model/dto/MatchEventCancelResponse.java
  src/main/java/com/matchday/matchdayserver/matchevent/repository/MatchEventRepository.java
  src/main/java/com/matchday/matchdayserver/matchevent/service/MatchEventCancelService.java
  src/main/java/com/matchday/matchdayserver/matchevent/service/MatchEventStrategy.java
Labels: ✨ Feat, 🎨 Modify

#143 [MAT-279] 팀 멤버 조회시 누적 출전, 득점, 경고 수 조회 되도록 추가
  src/main/java/com/matchday/matchdayserver/matchevent/repository/MatchEventRepository.java
  src/main/java/com/matchday/matchdayserver/matchuser/repository/MatchUserRepository.java
  src/main/java/com/matchday/matchdayserver/team/model/dto/response/TeamMemberResponse.java
  src/main/java/com/matchday/matchdayserver/team/service/TeamService.java
  src/main/java/com/matchday/matchdayserver/userteam/model/mapper/UserTeamMapper.java
  src/main/resources/application.yml
Labels: ✨ Feat

#144 feat: CORS 설정
  src/main/java/com/matchday/matchdayserver/common/Constants.java
  src/main/java/com/matchday/matchdayserver/config/WebConfig.java
Labels: ⚙ Config
