Repository matchday-team/matchday-api, pull requests merged in 2025-06, with the labels that each got.

#154 [MAT-333] 권한 체크 어노테이션 구현
  src/main/java/com/matchday/matchdayserver/auth/entity/RefreshToken.java
  src/main/java/com/matchday/matchdayserver/common/Aspect/CheckMatchAspect.java
  src/main/java/com/matchday/matchdayserver/common/Aspect/CheckTeamAspect.java
  src/main/java/com/matchday/matchdayserver/common/annotation/CheckMatch.java
  src/main/java/com/matchday/matchdayserver/common/annotation/CheckTeam.java
  src/main/java/com/matchday/matchdayserver/common/auth/CustomAccessDeniedHandler.java
  src/main/java/com/matchday/matchdayserver/common/exception/ApiExceptionHandler.java
  src/main/java/com/matchday/matchdayserver/common/response/AnnotationStatus.java
  src/main/java/com/matchday/matchdayserver/common/response/AuthStatus.java
  src/main/java/com/matchday/matchdayserver/common/response/DefaultStatus.java
  src/main/java/com/matchday/matchdayserver/config/SecurityConfig.java
  src/main/java/com/matchday/matchdayserver/config/SwaggerConfig.java
  src/main/java/com/matchday/matchdayserver/user/controller/UserController.java
  src/main/java/com/matchday/matchdayserver/user/model/dto/request/UpdateUserRoleRequest.java
  src/main/java/com/matchday/matchdayserver/user/model/dto/response/UpdateUserRoleResponse.java
  src/main/java/com/matchday/matchdayserver/user/model/entity/User.java
  src/main/java/com/matchday/matchdayserver/user/model/enums/Role.java
  src/main/java/com/matchday/matchdayserver/user/service/UserOpenApiService.java
  src/main/java/com/matchday/matchdayserver/user/service/UserService.java
Labels: ✨ Feat

#155 [MAT-314][MAT-315] Team,User 도메인 auth 적용
  src/main/java/com/matchday/matchdayserver/team/controller/TeamController.java
  src/main/java/com/matchday/matchdayserver/team/service/TeamService.java
  src/main/java/com/matchday/matchdayserver/user/controller/UserController.java
  src/main/java/com/matchday/matchdayserver/user/model/dto/request/UserJoinTeamRequest.java
Labels: ✨ Feat

#156 [MAT-316,317] MatchUser, Match 도메인 auth 적용
  src/main/java/com/matchday/matchdayserver/match/controller/MatchController.java
  src/main/java/com/matchday/matchdayserver/match/model/dto/request/MatchCreateRequest.java
  src/main/java/com/matchday/matchdayserver/matchevent/controller/MatchEventHistoryController.java
  src/main/java/com/matchday/matchdayserver/matchevent/model/dto/MatchEventRequest.java
  src/main/java/com/matchday/matchdayserver/matchevent/model/dto/MatchEventUserRequest.java
  src/main/java/com/matchday/matchdayserver/matchuser/controller/MatchUserController.java
  src/main/java/com/matchday/matchdayserver/matchuser/model/dto/MatchUserCreateRequest.java
  src/main/java/com/matchday/matchdayserver/matchuser/service/MatchUserService.java
  src/main/java/com/matchday/matchdayserver/team/service/TeamService.java
  src/main/java/com/matchday/matchdayserver/user/service/UserService.java
  src/main/resources/application.yml
  src/test/java/com/matchday/matchdayserver/matchuser/controller/MatchuserControllerCreateTest.java
Labels: ✨ Feat, ✅ Test

#157 modify: cors wild card 지원
  src/main/java/com/matchday/matchdayserver/common/Constants.java
  src/main/java/com/matchday/matchdayserver/config/WebConfig.java
Labels: ⚙ Config

#159 config: dev branch도 test 돌도록 수정
  .github/workflows/test.yml
Labels: ⚙ Config

#163 [MAT-370] ApiExceptionResponse 추가 및 에러 처리 로직에 ApiExceptionResponse로 변경
  src/main/java/com/matchday/matchdayserver/common/auth/CustomAccessDeniedHandler.java
  src/main/java/com/matchday/matchdayserver/common/exception/ApiExceptionHandler.java
  src/main/java/com/matchday/matchdayserver/common/exception/WebSocketExceptionHandler.java
  src/main/java/com/matchday/matchdayserver/common/response/ApiExceptionResponse.java
  src/main/java/com/matchday/matchdayserver/common/response/ApiResponse.java
Labels: ✨ Feat, 🔨 Refactor

#165 feat: workflow auth 코드 추가
  .github/workflows/deploy.yml
  .github/workflows/test.yml
  src/main/resources/application-test.yml
Labels: 🐞 Bug, 🗑️ Chore

#164 [MAT-372] 테스트 에러 터진 부분들 전체적으로 다 수정
  src/test/java/com/matchday/matchdayserver/match/model/dto/request/MockMatchCreateRequest.java
  src/test/java/com/matchday/matchdayserver/matchuser/controller/MatchuserControllerCreateTest.java
  src/test/java/com/matchday/matchdayserver/team/model/entity/MockTeam.java
  src/test/java/com/matchday/matchdayserver/user/controller/UserControllerCreateTest.java
  src/test/java/com/matchday/matchdayserver/user/model/entity/MockUser.java
Labels: 🐞 Bug, ✅ Test
